apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-hname
  labels:
    app: node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: echo-hname
        image: jsco2t/echo-srv