# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    M = 1 # max number of master nodes
    W = 3 # max number of worker nodes
    VER = '1.18.4' # k8s Version

    (1..M).each do |i|
        config.vm.define "m#{i}-k8s.snetsystems.co.kr" do |config|
            config.vm.box = "sysnet4admin/CentOS-k8s"
            config.vm.provider "virtualbox" do |vb|
                vb.name = "m#{i}-k8s.snetsystems.co.kr"
                vb.cpus = 2
                vb.memory = 2048
            end
            config.vm.hostname = "m#{i}-k8s.snetsystems.co.kr"
            config.vm.network "private_network", ip: "192.168.1.1#{i}"
            config.vm.network "forwarded_port", guest: 22, host:"6001#{i}", auto_correct:true, id:"ssh"
            
            config.vm.provision "shell", path: "config.sh"
            config.vm.provision "shell", path: "install.sh", args: VER
            config.vm.provision "shell", path: "master.sh"
        end
    end

    (1..W).each do |i|
        config.vm.define "w#{i}-k8s.snetsystems.co.kr" do |config|
            config.vm.box = "sysnet4admin/CentOS-k8s"
            config.vm.provider "virtualbox" do |vb|
                vb.name = "w#{i}-k8s.snetsystems.co.kr"
                vb.cpus = 1
                vb.memory = 1024
            end
            config.vm.hostname = "w#{i}-k8s.snetsystems.co.kr"
            config.vm.network "private_network", ip: "192.168.1.2#{i}"
            config.vm.network "forwarded_port", guest: 22, host:"6002#{i}", auto_correct:true, id:"ssh"
            
            config.vm.provision "shell", path: "config.sh"
            config.vm.provision "shell", path: "install.sh", args: VER
            config.vm.provision "shell", path: "worker.sh"
        end
    end

    # Hostmanager plugin
    config.hostmanager.enabled = true
    config.hostmanager.manage_guest = true

end